package com.hongdou.pojo;

import java.util.Date;

// Generated 2016-9-27 11:57:15 by Hibernate Tools 5.2.0.Beta1


/**
 * Admin generated by hbm2java
 */
public class Question implements java.io.Serializable {

	private Integer id;
	private String title;
	private String content;
	private Date publishtime ;
	private Integer type;
	private Integer userid;
	private Integer pageview;
	private Integer commentcount;
	private Integer status;
	private String author;

	public Question() {
	}

	public Question(Integer id, String title, String content,Date publishtime,Integer type,Integer userid ,Integer pageview,Integer commentcount,Integer status,String author) {
	
		this.id = id;
	    this.title = title;
	    this.content = content;
	    this.publishtime = publishtime;
	    this.type = type;
	    this.userid = userid;
	    this.pageview = pageview;
	    this.commentcount = commentcount;
	    this.status = status;
	    this.setAuthor(author);
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getPublishtime() {
		return publishtime;
	}

	public void setPublishtime(Date publishtime) {
		this.publishtime = publishtime;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Integer getPageview() {
		return pageview;
	}

	public void setPageview(Integer pageview) {
		this.pageview = pageview;
	}

	public Integer getCommentcount() {
		return commentcount;
	}

	public void setCommentcount(Integer commentcount) {
		this.commentcount = commentcount;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	
}
