package com.hongdou.pojo;
// Generated 2016-9-27 11:57:15 by Hibernate Tools 5.2.0.Beta1


/**
 * Admin generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private String name;
	private String password;
	private Integer sex;
	private String picture;
	private Integer status;

	public Users() {
	}

	public Users(Integer id, String name, String password,Integer status,Integer sex,String picture) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.status = status;
		this.sex = sex;
		this.picture = picture;
		
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getSex() {
		return sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getPicture() {
		return picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

}
